#!/bin/sh

DIR=`cd $(dirname $0); pwd`
MCC=$DIR/_minc99

usage()
{
  echo $flags
  echo "usage: mcc [cc flags] file.c" >&2
  exit 1
}

for i
do
  all="$all $i"
  file=$i
done

if test -z $file
then
  usage
fi

file2="${file%.*}"
# preprocessor
# use -include $DIR/stdio.h to override a single file
# and -I to include whole directory of overrides
cc -E -I $DIR/include $all -o $file2.p

# call minc
$MCC < $file2.p > $file2.q

if test $? -ne 0
then
# echo "error processing file $file" >&2
  exit 1
fi


