#!/bin/sh

DIR=`cd $(dirname $0); pwd`
PCC=$DIR/../cproc/cproc-qbe

usage()
{
  echo $flags
	echo "usage: mcc [cc flags] file.c" >&2
	exit 1
}

for i
do
  all="$all $i"
  file=$i
done

if test -z $file
then
	usage
fi

file2="${file%.*}"
cc -E -I $DIR/include $all -o $file2.p
$PCC < $file2.p > $file2.q

if test $? -ne 0
then
#	echo "error processing file $file" >&2
	exit 1
fi
