#!/bin/sh

DIR=`cd $(dirname $0); pwd`
QBE=$DIR/qbe

usage()
{
	echo "usage: qq file.q" >&2
	exit 1
}

for i
do
	case $i in
	-*)
		flags="$flags $i"
		;;
	*)
		if ! test -z $file
		then
			usage
		fi
		file=$i
		;;
	esac
done

if test -z $file
then
	usage
fi

file2="${file%.*}"
$QBE < $file2.q > $file2.s &&
cc -c $file2.s -o $file2.o
#ar rcs libsally.a sally.o

if test $? -ne 0
then
	echo "error processing file $file" >&2
	exit 1
fi

