#!/bin/sh

DIR=`cd $(dirname $0); pwd`
SRC_HOME=$DIR

rm -f $SRC_HOME/prime
rm -f $SRC_HOME/prime.o
rm -f $SRC_HOME/prime.s

../qq $SRC_HOME/prime.q
cc $SRC_HOME/prime.o -o $SRC_HOME/prime -lc
./prime
