#!/bin/sh

DIR=`cd $(dirname $0); pwd`
SRC_HOME=$DIR

rm -f $SRC_HOME/queen2
rm -f $SRC_HOME/queen2.o
rm -f $SRC_HOME/queen2.p
rm -f $SRC_HOME/queen2.q
rm -f $SRC_HOME/queen2.s

../mcc -I $SRC_HOME/../include $SRC_HOME/queen2.c
