#!/bin/sh

DIR=`cd $(dirname $0); pwd`
SRC_HOME=$DIR

rm -f $SRC_HOME/tmp
rm -f $SRC_HOME/tmp.o
rm -f $SRC_HOME/tmp.p
rm -f $SRC_HOME/tmp.q
rm -f $SRC_HOME/tmp.s

../mcc99 -I $SRC_HOME/../include $SRC_HOME/tmp.c
