#!/bin/sh

DIR=`cd $(dirname $0); pwd`
SRC_HOME=$DIR

rm -f $SRC_HOME/tmp_mc
rm -f $SRC_HOME/tmp_mc.o
rm -f $SRC_HOME/tmp_mc.p
rm -f $SRC_HOME/tmp_mc.q
rm -f $SRC_HOME/tmp_mc.s

../mcc -I $SRC_HOME/../include $SRC_HOME/tmp_mc.c
