#!/bin/sh

DIR=`cd $(dirname $0); pwd`
SRC_HOME=$DIR

rm -f $SRC_HOME/handcrafted
rm -f $SRC_HOME/handcrafted.o
rm -f $SRC_HOME/handcrafted.s

../qq $SRC_HOME/handcrafted.q
cc $SRC_HOME/handcrafted.o $SRC_HOME/crlf.o -o $SRC_HOME/handcrafted -lc
./handcrafted yo
